language : node_js
node_js:
 - stable
install:
- npm install

deploy:
   provider: npm
   email: you660555@gmail.com
   api_key: "$NPM_TOKEN"
   skip_cleanup: true
    on:
    tag: true
    all_branches: true
   tag: latest
